In [1]:
import pandas as pd
import numpy as np

from sklearn.svm import LinearSVC, SVC
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

In [3]:
df = pd.read_csv('../After_EDA_data/Light_text.csv')

In [4]:
df

,uid,profile,anime_uid,score,scores,text
0,255938,DesolatePsyche,34096,8,"{'Overall': '8', 'Story': '8', 'Animation': '8...",first things first my reviews system is explai...
1,259117,baekbeans,34599,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",let me start off by saying that made in abyss ...
2,253664,skrn,28891,7,"{'Overall': '7', 'Story': '7', 'Animation': '9...",10 it is great especially the actions during t...
3,8254,edgewalker00,2904,9,"{'Overall': '9', 'Story': '9', 'Animation': '9...",story taking place 1 yr from where season 1 tr...
4,291149,aManOfCulture99,4181,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",kyoto animations greatest strength is being ab...
...,...,...,...,...,...,...
192107,240067,Unicorn819,1281,9,"{'Overall': '9', 'Story': '5', 'Animation': '1...",ok this anime is pretty old but here s the bac...
192108,285777,ShizzoSVH,1281,9,"{'Overall': '9', 'Story': '7', 'Animation': '9...",the dub for this anime is made this anime a fu...
192109,286904,AlluMan96,1281,3,"{'Overall': '3', 'Story': '3', 'Animation': '1...",some might argue that doing a review of a show...
192110,287903,AgentK300,1281,10,"{'Overall': '10', 'Story': '3', 'Animation': '...",absolutely hilarious i accidentally came acros...
192111,299323,Scarlet012,1281,9,"{'Overall': '9', 'Story': '7', 'Animation': '8...",this will be a review for the english dubbed v...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192112 entries, 0 to 192111
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   uid        192112 non-null  int64
 1   profile    192112 non-null  object
 2   anime_uid  192112 non-null  int64
 3   score      192112 non-null  int64
 4   scores     192112 non-null  object
 5   text       192112 non-null  object
dtypes: int64(3), object(3)
memory usage: 8.8+ MB

In [5]:
df.columns

Index(['uid', 'profile', 'anime_uid', 'score', 'scores', 'text'], dtype='object')

In [6]:
df.shape

(192112, 6)

In [7]:
df

,uid,profile,anime_uid,score,scores,text
0,255938,DesolatePsyche,34096,8,"{'Overall': '8', 'Story': '8', 'Animation': '8...",first things first my reviews system is explai...
1,259117,baekbeans,34599,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",let me start off by saying that made in abyss ...
2,253664,skrn,28891,7,"{'Overall': '7', 'Story': '7', 'Animation': '9...",10 it is great especially the actions during t...
3,8254,edgewalker00,2904,9,"{'Overall': '9', 'Story': '9', 'Animation': '9...",story taking place 1 yr from where season 1 tr...
4,291149,aManOfCulture99,4181,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",kyoto animations greatest strength is being ab...
...,...,...,...,...,...,...
192107,240067,Unicorn819,1281,9,"{'Overall': '9', 'Story': '5', 'Animation': '1...",ok this anime is pretty old but here s the bac...
192108,285777,ShizzoSVH,1281,9,"{'Overall': '9', 'Story': '7', 'Animation': '9...",the dub for this anime is made this anime a fu...
192109,286904,AlluMan96,1281,3,"{'Overall': '3', 'Story': '3', 'Animation': '1...",some might argue that doing a review of a show...
192110,287903,AgentK300,1281,10,"{'Overall': '10', 'Story': '3', 'Animation': '...",absolutely hilarious i accidentally came acros...
192111,299323,Scarlet012,1281,9,"{'Overall': '9', 'Story': '7', 'Animation': '8...",this will be a review for the english dubbed v...

In [8]:
def classification(text):
    if text >= 5:
        return 'Good'
    return "Bad"

In [9]:
df['target'] = df['score'].apply(classification)

In [10]:
df['target'].value_counts()

target
Good    169994
Bad      22118
Name: count, dtype: int64

In [11]:
df

,uid,profile,anime_uid,score,scores,text,target
0,255938,DesolatePsyche,34096,8,"{'Overall': '8', 'Story': '8', 'Animation': '8...",first things first my reviews system is explai...,Good
1,259117,baekbeans,34599,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",let me start off by saying that made in abyss ...,Good
2,253664,skrn,28891,7,"{'Overall': '7', 'Story': '7', 'Animation': '9...",10 it is great especially the actions during t...,Good
3,8254,edgewalker00,2904,9,"{'Overall': '9', 'Story': '9', 'Animation': '9...",story taking place 1 yr from where season 1 tr...,Good
4,291149,aManOfCulture99,4181,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",kyoto animations greatest strength is being ab...,Good
...,...,...,...,...,...,...,...
192107,240067,Unicorn819,1281,9,"{'Overall': '9', 'Story': '5', 'Animation': '1...",ok this anime is pretty old but here s the bac...,Good
192108,285777,ShizzoSVH,1281,9,"{'Overall': '9', 'Story': '7', 'Animation': '9...",the dub for this anime is made this anime a fu...,Good
192109,286904,AlluMan96,1281,3,"{'Overall': '3', 'Story': '3', 'Animation': '1...",some might argue that doing a review of a show...,Bad
192110,287903,AgentK300,1281,10,"{'Overall': '10', 'Story': '3', 'Animation': '...",absolutely hilarious i accidentally came acros...,Good
192111,299323,Scarlet012,1281,9,"{'Overall': '9', 'Story': '7', 'Animation': '8...",this will be a review for the english dubbed v...,Good

In [12]:
df['text'].duplicated().sample(10)

77830     False
65654     False
131945     True
17306     False
93059     False
107940    False
7564      False
178609     True
139005     True
76801     False
Name: text, dtype: bool

In [13]:
df['text'].duplicated().sum()

np.int64(61764)

In [14]:
df['text'] = df['text'].drop_duplicates()

In [15]:
df = df.dropna()

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 130348 entries, 0 to 182637
Data columns (total 7 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   uid        130348 non-null  int64
 1   profile    130348 non-null  object
 2   anime_uid  130348 non-null  int64
 3   score      130348 non-null  int64
 4   scores     130348 non-null  object
 5   text       130348 non-null  object
 6   target     130348 non-null  object
dtypes: int64(3), object(4)
memory usage: 8.0+ MB

In [17]:
df_majority = df[df['target'] == 'Good']
df_minority = df[df['target']== 'Bad']

In [18]:
df_reduced = df_majority.sample(n=len(df_minority), random_state=42)

In [19]:
df_balanced = pd.concat([df_reduced, df_minority]).sample(frac=1, random_state=42)

In [20]:
df_balanced

,uid,profile,anime_uid,score,scores,text,target
143790,299288,TheeSilent,37799,2,"{'Overall': '2', 'Story': '2', 'Animation': '5...",everything in a nutshell don t you hate it whe...,Bad
17776,294930,venusinfleursx,47,3,"{'Overall': '3', 'Story': '3', 'Animation': '3...",pioneering classic groundbreaking compelling m...,Bad
7647,206255,issei4,30276,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",from where should i start about one punch man ...,Good
33422,212047,Andreas_Senpai,12355,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",ok so i just found out about this movie a few ...,Good
51612,128261,vollminator,5681,7,"{'Overall': '7', 'Story': '6', 'Animation': '1...",summer wars feels fun and enjoyable when showi...,Good
...,...,...,...,...,...,...,...
157456,255255,Tyrannicswine117,16700,8,"{'Overall': '8', 'Story': '8', 'Animation': '8...",warning possible spoilers the final piece of t...,Good
76169,281422,farmanator,3025,7,"{'Overall': '7', 'Story': '7', 'Animation': '9...",this anime is fun nothing more nothing less no...,Good
28591,123731,Aeroblip,11981,9,"{'Overall': '9', 'Story': '0', 'Animation': '0...",puella magi madoka magica the movie part iii r...,Good
162778,23210,Rakuen42,3859,8,"{'Overall': '8', 'Story': '8', 'Animation': '8...",himitsu s basic premise is interesting and mak...,Good
37225,106297,mushroomlee18,9253,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",el psy congroo boy this was a fun time travel ...,Good

In [21]:
df_balanced = df_balanced.reset_index(drop=True)

In [22]:
df_balanced

,uid,profile,anime_uid,score,scores,text,target
0,299288,TheeSilent,37799,2,"{'Overall': '2', 'Story': '2', 'Animation': '5...",everything in a nutshell don t you hate it whe...,Bad
1,294930,venusinfleursx,47,3,"{'Overall': '3', 'Story': '3', 'Animation': '3...",pioneering classic groundbreaking compelling m...,Bad
2,206255,issei4,30276,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",from where should i start about one punch man ...,Good
3,212047,Andreas_Senpai,12355,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",ok so i just found out about this movie a few ...,Good
4,128261,vollminator,5681,7,"{'Overall': '7', 'Story': '6', 'Animation': '1...",summer wars feels fun and enjoyable when showi...,Good
...,...,...,...,...,...,...,...
35317,255255,Tyrannicswine117,16700,8,"{'Overall': '8', 'Story': '8', 'Animation': '8...",warning possible spoilers the final piece of t...,Good
35318,281422,farmanator,3025,7,"{'Overall': '7', 'Story': '7', 'Animation': '9...",this anime is fun nothing more nothing less no...,Good
35319,123731,Aeroblip,11981,9,"{'Overall': '9', 'Story': '0', 'Animation': '0...",puella magi madoka magica the movie part iii r...,Good
35320,23210,Rakuen42,3859,8,"{'Overall': '8', 'Story': '8', 'Animation': '8...",himitsu s basic premise is interesting and mak...,Good
35321,106297,mushroomlee18,9253,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",el psy congroo boy this was a fun time travel ...,Good

In [23]:
df_balanced['text'].duplicated().sum()

np.int64(0)

In [24]:
df_balanced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35322 entries, 0 to 35321
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   uid        35322 non-null  int64
 1   profile    35322 non-null  object
 2   anime_uid  35322 non-null  int64
 3   score      35322 non-null  int64
 4   scores     35322 non-null  object
 5   text       35322 non-null  object
 6   target     35322 non-null  object
dtypes: int64(3), object(4)
memory usage: 1.9+ MB

In [25]:
x = df_balanced['text']
y = df_balanced['target']

In [26]:
le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y_encoded, test_size=0.3, stratify=y_encoded, random_state=42
)

In [28]:
tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2)
)

In [29]:
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [30]:
svc = LinearSVC()

svc.fit(X_train_tfidf, y_train)

LinearSVC()

In [31]:
y_pred = svc.predict(X_test_tfidf)
y_score = svc.decision_function(X_test_tfidf)

In [32]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.86      0.86      5299
           1       0.86      0.86      0.86      5298

    accuracy                           0.86     10597
   macro avg       0.86      0.86      0.86     10597
weighted avg       0.86      0.86      0.86     10597

In [33]:
print(confusion_matrix(y_test, y_pred))

[[4552  747]
 [ 763 4535]]

In [34]:
print(roc_auc_score(y_test, y_score))

0.9303324466086217