In [1]:
# %pip install xgboost

In [2]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('../After_EDA_data/Light_text.csv')

In [4]:
df

,uid,profile,anime_uid,score,scores,text
0,255938,DesolatePsyche,34096,8,"{'Overall': '8', 'Story': '8', 'Animation': '8...",first things first my reviews system is explai...
1,259117,baekbeans,34599,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",let me start off by saying that made in abyss ...
2,253664,skrn,28891,7,"{'Overall': '7', 'Story': '7', 'Animation': '9...",10 it is great especially the actions during t...
3,8254,edgewalker00,2904,9,"{'Overall': '9', 'Story': '9', 'Animation': '9...",story taking place 1 yr from where season 1 tr...
4,291149,aManOfCulture99,4181,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",kyoto animations greatest strength is being ab...
...,...,...,...,...,...,...
192107,240067,Unicorn819,1281,9,"{'Overall': '9', 'Story': '5', 'Animation': '1...",ok this anime is pretty old but here s the bac...
192108,285777,ShizzoSVH,1281,9,"{'Overall': '9', 'Story': '7', 'Animation': '9...",the dub for this anime is made this anime a fu...
192109,286904,AlluMan96,1281,3,"{'Overall': '3', 'Story': '3', 'Animation': '1...",some might argue that doing a review of a show...
192110,287903,AgentK300,1281,10,"{'Overall': '10', 'Story': '3', 'Animation': '...",absolutely hilarious i accidentally came acros...
192111,299323,Scarlet012,1281,9,"{'Overall': '9', 'Story': '7', 'Animation': '8...",this will be a review for the english dubbed v...

In [5]:
def classification(score):
    if score > 6:
        return 'Good'
    elif score > 4:
        return 'Neutral'
    else:
        return 'Bad'

In [6]:
df['target'] = df['score'].apply(classification)

In [7]:
df

,uid,profile,anime_uid,score,scores,text,target
0,255938,DesolatePsyche,34096,8,"{'Overall': '8', 'Story': '8', 'Animation': '8...",first things first my reviews system is explai...,Good
1,259117,baekbeans,34599,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",let me start off by saying that made in abyss ...,Good
2,253664,skrn,28891,7,"{'Overall': '7', 'Story': '7', 'Animation': '9...",10 it is great especially the actions during t...,Good
3,8254,edgewalker00,2904,9,"{'Overall': '9', 'Story': '9', 'Animation': '9...",story taking place 1 yr from where season 1 tr...,Good
4,291149,aManOfCulture99,4181,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",kyoto animations greatest strength is being ab...,Good
...,...,...,...,...,...,...,...
192107,240067,Unicorn819,1281,9,"{'Overall': '9', 'Story': '5', 'Animation': '1...",ok this anime is pretty old but here s the bac...,Good
192108,285777,ShizzoSVH,1281,9,"{'Overall': '9', 'Story': '7', 'Animation': '9...",the dub for this anime is made this anime a fu...,Good
192109,286904,AlluMan96,1281,3,"{'Overall': '3', 'Story': '3', 'Animation': '1...",some might argue that doing a review of a show...,Bad
192110,287903,AgentK300,1281,10,"{'Overall': '10', 'Story': '3', 'Animation': '...",absolutely hilarious i accidentally came acros...,Good
192111,299323,Scarlet012,1281,9,"{'Overall': '9', 'Story': '7', 'Animation': '8...",this will be a review for the english dubbed v...,Good

In [8]:
df['target'].value_counts()

target
Good       142343
Neutral     27651
Bad         22118
Name: count, dtype: int64

In [9]:
df_majority = df[df['target'] == 'Good']
df_minority = df[df['target'] == 'Bad']
df_neutral = df[df['target'] == 'Neutral']

In [10]:
df_reduced_majority = df_majority.sample(n=len(df_neutral), random_state=42)

In [11]:
df_reduced_majority.value_counts()

uid     profile           anime_uid  score  scores                                                                                                   text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             target

In [12]:
df_balanced = pd.concat([df_reduced_majority, df_minority, df_neutral]).sample(frac=1, random_state=42)

In [13]:
df_balanced['target'].value_counts()

target
Good       27651
Neutral    27651
Bad        22118
Name: count, dtype: int64

In [14]:
df_balanced = df_balanced.reset_index(drop=True)

In [15]:
df_balanced

,uid,profile,anime_uid,score,scores,text,target
0,13952,KillerMan91,73,9,"{'Overall': '9', 'Story': '9', 'Animation': '9...",full metal panic! tsr is 13 episodes long sequ...,Good
1,305201,Grizzziff,21877,8,"{'Overall': '8', 'Story': '8', 'Animation': '8...",what a clever little nuance factory cash grab ...,Good
2,243817,Fircoal,33089,8,"{'Overall': '8', 'Story': '9', 'Animation': '2...",i have a confession to make when i watched the...,Good
3,284471,Botmj,36214,4,"{'Overall': '4', 'Story': '1', 'Animation': '1...",the only good thing i have to say about this i...,Bad
4,291301,BabyGirl06301,31765,8,"{'Overall': '8', 'Story': '9', 'Animation': '1...",i thought this movie was a wonderful addition ...,Good
...,...,...,...,...,...,...,...
77415,141887,Flueckli,10098,7,"{'Overall': '7', 'Story': '6', 'Animation': '4...",don t expect too much out of these shortstorie...,Good
77416,226574,FAKEANIMEGIRL,2724,6,"{'Overall': '6', 'Story': '0', 'Animation': '0...",gainax s two short films made for the science ...,Neutral
77417,241425,Rizkiawan-kun,21995,6,"{'Overall': '6', 'Story': '7', 'Animation': '6...",in short this anime is not more than one shouj...,Neutral
77418,18387,boundtotomorrow,853,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",to put it simply i wish more if not all animes...,Good
77419,217796,Fake_Williams,249,8,"{'Overall': '8', 'Story': '8', 'Animation': '8...",in terms of what i think about this anime i be...,Good

In [16]:
x = df_balanced['text']
y = df_balanced['target']

In [17]:
le = LabelEncoder()
y_encoded = le.fit_transform(y)

print(le.classes_)

['Bad' 'Good' 'Neutral']

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y_encoded, test_size=0.3, random_state=42, stratify=y_encoded
)

In [19]:
df_balanced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77420 entries, 0 to 77419
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   uid        77420 non-null  int64
 1   profile    77420 non-null  object
 2   anime_uid  77420 non-null  int64
 3   score      77420 non-null  int64
 4   scores     77420 non-null  object
 5   text       77420 non-null  object
 6   target     77420 non-null  object
dtypes: int64(3), object(4)
memory usage: 4.1+ MB

In [20]:
tfidf = TfidfVectorizer(
    max_features=1000,
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [21]:
model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.5,
    subsample=0.8,
    colsample_bytree=0.5,
    eval_metric='logloss'
)

model.fit(X_train_tfidf, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.5, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.5, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [22]:
y_pred = model.predict(X_test_tfidf)
y_pred_labels = le.inverse_transform(y_pred)
print(y_pred_labels)

['Good' 'Neutral' 'Bad' ... 'Neutral' 'Good' 'Bad']

In [23]:
print(classification_report(y_test, y_pred, target_names=le.classes_))

              precision    recall  f1-score   support

         Bad       0.73      0.67      0.70      6636
        Good       0.78      0.80      0.79      8295
     Neutral       0.64      0.67      0.66      8295

    accuracy                           0.72     23226
   macro avg       0.72      0.71      0.72     23226
weighted avg       0.72      0.72      0.72     23226

In [24]:
print(confusion_matrix(y_test, y_pred))

[[4474  446 1716]
 [ 314 6614 1367]
 [1335 1403 5557]]

In [25]:
y_prob = model.predict_proba(X_test_tfidf)

In [26]:
roc_auc = roc_auc_score(
    y_test,
    y_prob,
    multi_class='ovr',
    average='macro'
)

print("ROC AUC:", roc_auc)

ROC AUC: 0.8773314187193982