In [1]:
import numpy as np
import pandas as pd

import re

In [2]:
df = pd.read_csv('archive/reviews.csv')

In [3]:
df

,uid,profile,anime_uid,text,score,scores,link
0,255938,DesolatePsyche,34096,\n \n \n \n ...,8,"{'Overall': '8', 'Story': '8', 'Animation': '8...",https://myanimelist.net/reviews.php?id=255938
1,259117,baekbeans,34599,\n \n \n \n ...,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",https://myanimelist.net/reviews.php?id=259117
2,253664,skrn,28891,\n \n \n \n ...,7,"{'Overall': '7', 'Story': '7', 'Animation': '9...",https://myanimelist.net/reviews.php?id=253664
3,8254,edgewalker00,2904,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '9', 'Animation': '9...",https://myanimelist.net/reviews.php?id=8254
4,291149,aManOfCulture99,4181,\n \n \n \n ...,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",https://myanimelist.net/reviews.php?id=291149
...,...,...,...,...,...,...,...
192107,240067,Unicorn819,1281,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '5', 'Animation': '1...",https://myanimelist.net/reviews.php?id=240067
192108,285777,ShizzoSVH,1281,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '7', 'Animation': '9...",https://myanimelist.net/reviews.php?id=285777
192109,286904,AlluMan96,1281,\n \n \n \n ...,3,"{'Overall': '3', 'Story': '3', 'Animation': '1...",https://myanimelist.net/reviews.php?id=286904
192110,287903,AgentK300,1281,\n \n \n \n ...,10,"{'Overall': '10', 'Story': '3', 'Animation': '...",https://myanimelist.net/reviews.php?id=287903
192111,299323,Scarlet012,1281,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '7', 'Animation': '8...",https://myanimelist.net/reviews.php?id=299323

In [4]:
df = df.drop(columns=['link'])

In [5]:
df

,uid,profile,anime_uid,text,score,scores
0,255938,DesolatePsyche,34096,\n \n \n \n ...,8,"{'Overall': '8', 'Story': '8', 'Animation': '8..."
1,259117,baekbeans,34599,\n \n \n \n ...,10,"{'Overall': '10', 'Story': '10', 'Animation': ..."
2,253664,skrn,28891,\n \n \n \n ...,7,"{'Overall': '7', 'Story': '7', 'Animation': '9..."
3,8254,edgewalker00,2904,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '9', 'Animation': '9..."
4,291149,aManOfCulture99,4181,\n \n \n \n ...,10,"{'Overall': '10', 'Story': '10', 'Animation': ..."
...,...,...,...,...,...,...
192107,240067,Unicorn819,1281,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '5', 'Animation': '1..."
192108,285777,ShizzoSVH,1281,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '7', 'Animation': '9..."
192109,286904,AlluMan96,1281,\n \n \n \n ...,3,"{'Overall': '3', 'Story': '3', 'Animation': '1..."
192110,287903,AgentK300,1281,\n \n \n \n ...,10,"{'Overall': '10', 'Story': '3', 'Animation': '..."
192111,299323,Scarlet012,1281,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '7', 'Animation': '8..."

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192112 entries, 0 to 192111
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   uid        192112 non-null  int64
 1   profile    192112 non-null  object
 2   anime_uid  192112 non-null  int64
 3   text       192112 non-null  object
 4   score      192112 non-null  int64
 5   scores     192112 non-null  object
dtypes: int64(3), object(3)
memory usage: 8.8+ MB

In [7]:
df.shape

(192112, 6)

In [8]:
df = df.dropna()

In [9]:
df

,uid,profile,anime_uid,text,score,scores
0,255938,DesolatePsyche,34096,\n \n \n \n ...,8,"{'Overall': '8', 'Story': '8', 'Animation': '8..."
1,259117,baekbeans,34599,\n \n \n \n ...,10,"{'Overall': '10', 'Story': '10', 'Animation': ..."
2,253664,skrn,28891,\n \n \n \n ...,7,"{'Overall': '7', 'Story': '7', 'Animation': '9..."
3,8254,edgewalker00,2904,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '9', 'Animation': '9..."
4,291149,aManOfCulture99,4181,\n \n \n \n ...,10,"{'Overall': '10', 'Story': '10', 'Animation': ..."
...,...,...,...,...,...,...
192107,240067,Unicorn819,1281,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '5', 'Animation': '1..."
192108,285777,ShizzoSVH,1281,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '7', 'Animation': '9..."
192109,286904,AlluMan96,1281,\n \n \n \n ...,3,"{'Overall': '3', 'Story': '3', 'Animation': '1..."
192110,287903,AgentK300,1281,\n \n \n \n ...,10,"{'Overall': '10', 'Story': '3', 'Animation': '..."
192111,299323,Scarlet012,1281,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '7', 'Animation': '8..."

In [10]:
df['uid'].nunique()

130519

In [11]:
df['profile'].nunique()

47885

In [12]:
df['anime_uid'].nunique()

8113

In [13]:
df.shape

(192112, 6)

In [14]:
df['char_count'] = df['text'].str.len()
df['word_count'] = df['text'].str.split().str.len()

df[['char_count', 'word_count']].describe()

          char_count     word_count
count  192112.000000  192112.000000
mean     3385.454995     507.641553
std      2783.840884     483.055892
min       656.000000      27.000000
25%      1630.000000     202.000000
50%      2559.000000     365.000000
75%      4165.000000     645.000000
max     65754.000000   11488.000000

In [15]:
df[['char_count', 'word_count']].quantile([0.15, 0.85])

      char_count  word_count
0.15     1369.00       156.0
0.85     5406.35       861.0

In [16]:
df[['char_count', 'word_count']].quantile([0.1, 0.9])

     char_count  word_count
0.1      1260.0       137.0
0.9      6444.0      1040.0

In [17]:
df[['char_count', 'word_count']].quantile([0.05, 0.95])

      char_count  word_count
0.05      1152.0       119.0
0.95      8279.0      1355.0

In [18]:
df['char_count'] = pd.cut(df['char_count'], bins=10)
df['word_count'] = pd.cut(df['word_count'], bins=10)

In [19]:
df['char_count'].value_counts().sort_index()

char_count
(590.902, 7165.8]     177554
(7165.8, 13675.6]      12614
(13675.6, 20185.4]      1382
(20185.4, 26695.2]       362
(26695.2, 33205.0]       122
(33205.0, 39714.8]        34
(39714.8, 46224.6]        20
(46224.6, 52734.4]        15
(52734.4, 59244.2]         4
(59244.2, 65754.0]         5
Name: count, dtype: int64

In [20]:
df['word_count'].value_counts().sort_index()

word_count
(15.539, 1173.1]      177839
(1173.1, 2319.2]       12400
(2319.2, 3465.3]        1346
(3465.3, 4611.4]         345
(4611.4, 5757.5]         102
(5757.5, 6903.6]          39
(6903.6, 8049.7]          19
(8049.7, 9195.8]          16
(9195.8, 10341.9]          2
(10341.9, 11488.0]         4
Name: count, dtype: int64

In [21]:
def basic_clean(text):
    if pd.isna(text):
        return ''

    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    text = text.strip()

    return text

df['clean_text'] = df['text'].apply(basic_clean)

In [22]:
df['clean_word_count'] = df['clean_text'].str.split().str.len()

In [23]:
df['clean_word_count'] = pd.cut(df['clean_word_count'], bins=10)

df['clean_word_count'].value_counts().sort_index()

clean_word_count
(15.324, 1194.6]      177478
(1194.6, 2362.2]       12705
(2362.2, 3529.8]        1384
(3529.8, 4697.4]         362
(4697.4, 5865.0]         103
(5865.0, 7032.6]          38
(7032.6, 8200.2]          18
(8200.2, 9367.8]          16
(9367.8, 10535.4]          4
(10535.4, 11703.0]         4
Name: count, dtype: int64

In [24]:
df

,uid,profile,anime_uid,text,score,scores,char_count,word_count,clean_text,clean_word_count
0,255938,DesolatePsyche,34096,\n \n \n \n ...,8,"{'Overall': '8', 'Story': '8', 'Animation': '8...","(590.902, 7165.8]","(15.539, 1173.1]",more pics overall 8 story 8 animation 8 sound ...,"(15.324, 1194.6]"
1,259117,baekbeans,34599,\n \n \n \n ...,10,"{'Overall': '10', 'Story': '10', 'Animation': ...","(590.902, 7165.8]","(15.539, 1173.1]",more pics overall 10 story 10 animation 10 sou...,"(15.324, 1194.6]"
2,253664,skrn,28891,\n \n \n \n ...,7,"{'Overall': '7', 'Story': '7', 'Animation': '9...","(590.902, 7165.8]","(15.539, 1173.1]",more pics overall 7 story 7 animation 9 sound ...,"(15.324, 1194.6]"
3,8254,edgewalker00,2904,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '9', 'Animation': '9...","(590.902, 7165.8]","(15.539, 1173.1]",more pics overall 9 story 9 animation 9 sound ...,"(15.324, 1194.6]"
4,291149,aManOfCulture99,4181,\n \n \n \n ...,10,"{'Overall': '10', 'Story': '10', 'Animation': ...","(590.902, 7165.8]","(15.539, 1173.1]",more pics overall 10 story 10 animation 8 soun...,"(15.324, 1194.6]"
...,...,...,...,...,...,...,...,...,...,...
192107,240067,Unicorn819,1281,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '5', 'Animation': '1...","(590.902, 7165.8]","(15.539, 1173.1]",more pics overall 9 story 5 animation 10 sound...,"(15.324, 1194.6]"
192108,285777,ShizzoSVH,1281,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '7', 'Animation': '9...","(590.902, 7165.8]","(15.539, 1173.1]",more pics overall 9 story 7 animation 9 sound ...,"(15.324, 1194.6]"
192109,286904,AlluMan96,1281,\n \n \n \n ...,3,"{'Overall': '3', 'Story': '3', 'Animation': '1...","(7165.8, 13675.6]","(1173.1, 2319.2]",more pics overall 3 story 3 animation 1 sound ...,"(1194.6, 2362.2]"
192110,287903,AgentK300,1281,\n \n \n \n ...,10,"{'Overall': '10', 'Story': '3', 'Animation': '...","(590.902, 7165.8]","(15.539, 1173.1]",more pics overall 10 story 3 animation 3 sound...,"(15.324, 1194.6]"
192111,299323,Scarlet012,1281,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '7', 'Animation': '8...","(590.902, 7165.8]","(15.539, 1173.1]",more pics overall 9 story 7 animation 8 sound ...,"(15.324, 1194.6]"

In [25]:
df['clean_text']

0         more pics overall 8 story 8 animation 8 sound ...
1         more pics overall 10 story 10 animation 10 sou...
2         more pics overall 7 story 7 animation 9 sound ...
3         more pics overall 9 story 9 animation 9 sound ...
4         more pics overall 10 story 10 animation 8 soun...
                                ...
192107    more pics overall 9 story 5 animation 10 sound...
192108    more pics overall 9 story 7 animation 9 sound ...
192109    more pics overall 3 story 3 animation 1 sound ...
192110    more pics overall 10 story 3 animation 3 sound...
192111    more pics overall 9 story 7 animation 8 sound ...
Name: clean_text, Length: 192112, dtype: object

In [26]:
df['clean_text'].sample(10)

188192    more pics overall 8 story 8 animation 8 sound ...
187899    more pics overall 5 story 0 animation 0 sound ...
165955    more pics overall 10 story 9 animation 10 soun...
12160     more pics overall 8 story 8 animation 8 sound ...
58072     more pics overall 10 story 7 animation 10 soun...
59678     more pics overall 7 story 0 animation 0 sound ...
88022     more pics overall 8 story 8 animation 9 sound ...
17644     more pics overall 4 story 2 animation 9 sound ...
24177     more pics overall 8 story 8 animation 7 sound ...
132138    more pics overall 8 story 10 animation 7 sound...
Name: clean_text, dtype: object

In [27]:
df['clean_text'].sample(10)

123035    more pics overall 6 story 7 animation 6 sound ...
72791     more pics overall 2 story 2 animation 2 sound ...
182376    more pics overall 10 story 10 animation 10 sou...
86715     more pics overall 10 story 8 animation 9 sound...
52244     more pics overall 10 story 10 animation 10 sou...
55887     more pics overall 7 story 5 animation 8 sound ...
115870    more pics overall 6 story 6 animation 9 sound ...
7635      more pics overall 9 story 0 animation 0 sound ...
23800     more pics overall 6 story 4 animation 8 sound ...
23863     more pics overall 10 story 9 animation 7 sound...
Name: clean_text, dtype: object

In [28]:
def remove_rating_block(text):
    if pd.isna(text):
        return ''

    text = text.lower()
    text = re.sub(r'\bmore pics\b', '', text)
    text = re.sub(r'\b(overall|story|animation|sound|character|enjoyment)\s+\d+\b', '', text, flags=re.IGNORECASE)
    text = re.sub(r'[^a-zA-Z0-9\s!?]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    text = text.strip()

    return text

df['cleaner_text'] = df['text'].apply(remove_rating_block)

In [29]:
df[['clean_text', 'cleaner_text']].sample(10)

,clean_text,cleaner_text
137495,more pics overall 3 story 2 animation 4 sound ...,mizuryuu kei land! it is the perfect example o...
137598,more pics overall 6 story 6 animation 3 sound ...,i wasn t too sure about this 4 parter when i s...
172944,more pics overall 9 story 10 animation 10 soun...,intro urara meirocho is based off a rather sho...
98139,more pics overall 10 story 9 animation 9 sound...,yahoo d unfortunately no season 2 has been ann...
191568,more pics overall 8 story 8 animation 9 sound ...,i will write this little review to the people ...
168140,more pics overall 5 story 6 animation 7 sound ...,i ve always had this habit of picking up stuff...
88065,more pics overall 8 story 9 animation 8 sound ...,this series is such a hidden gem this season i...
79758,more pics overall 9 story 9 animation 8 sound ...,i started watching this anime on a tiresome da...
74541,more pics overall 5 story 6 animation 7 sound ...,moral of the story if you cheat women are even...
156682,more pics overall 9 story 8 animation 9 sound ...,spoiler!!! it s winter december 17th and the d...

In [30]:
df['cleaner_text'].duplicated().sum()

np.int64(61764)

In [31]:
df['word_count'] = df['clean_text'].str.split().str.len()
df['clean_word_count'] = df['cleaner_text'].str.split().str.len()

df[['word_count', 'clean_word_count']].describe()

          word_count  clean_word_count
count  192112.000000     192112.000000
mean      522.200336        507.997621
std       497.349705        497.348350
min        27.000000         13.000000
25%       207.000000        193.000000
50%       375.000000        361.000000
75%       664.000000        650.000000
max     11703.000000      11689.000000

In [32]:
df['word_count'] = pd.cut(df['word_count'], bins=10)
df['clean_word_count'] = pd.cut(df['clean_word_count'], bins=10)

In [33]:
df['word_count'].value_counts().sort_index()

word_count
(15.324, 1194.6]      177478
(1194.6, 2362.2]       12705
(2362.2, 3529.8]        1384
(3529.8, 4697.4]         362
(4697.4, 5865.0]         103
(5865.0, 7032.6]          38
(7032.6, 8200.2]          18
(8200.2, 9367.8]          16
(9367.8, 10535.4]          4
(10535.4, 11703.0]         4
Name: count, dtype: int64

In [34]:
df['clean_word_count'].value_counts().sort_index()

clean_word_count
(1.324, 1180.6]       177487
(1180.6, 2348.2]       12695
(2348.2, 3515.8]        1385
(3515.8, 4683.4]         362
(4683.4, 5851.0]         103
(5851.0, 7018.6]          38
(7018.6, 8186.2]          18
(8186.2, 9353.8]          16
(9353.8, 10521.4]          4
(10521.4, 11689.0]         4
Name: count, dtype: int64

In [35]:
df.shape

(192112, 11)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192112 entries, 0 to 192111
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   uid               192112 non-null  int64
 1   profile           192112 non-null  object
 2   anime_uid         192112 non-null  int64
 3   text              192112 non-null  object
 4   score             192112 non-null  int64
 5   scores            192112 non-null  object
 6   char_count        192112 non-null  category
 7   word_count        192112 non-null  category
 8   clean_text        192112 non-null  object
 9   clean_word_count  192112 non-null  category
 10  cleaner_text      192112 non-null  object
dtypes: category(3), int64(3), object(5)
memory usage: 12.3+ MB

In [37]:
df = df.reset_index(drop=True)

In [38]:
df

,uid,profile,anime_uid,text,score,scores,char_count,word_count,clean_text,clean_word_count,cleaner_text
0,255938,DesolatePsyche,34096,\n \n \n \n ...,8,"{'Overall': '8', 'Story': '8', 'Animation': '8...","(590.902, 7165.8]","(15.324, 1194.6]",more pics overall 8 story 8 animation 8 sound ...,"(1.324, 1180.6]",first things first my reviews system is explai...
1,259117,baekbeans,34599,\n \n \n \n ...,10,"{'Overall': '10', 'Story': '10', 'Animation': ...","(590.902, 7165.8]","(15.324, 1194.6]",more pics overall 10 story 10 animation 10 sou...,"(1.324, 1180.6]",let me start off by saying that made in abyss ...
2,253664,skrn,28891,\n \n \n \n ...,7,"{'Overall': '7', 'Story': '7', 'Animation': '9...","(590.902, 7165.8]","(15.324, 1194.6]",more pics overall 7 story 7 animation 9 sound ...,"(1.324, 1180.6]",art 9 10 it is great especially the actions du...
3,8254,edgewalker00,2904,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '9', 'Animation': '9...","(590.902, 7165.8]","(15.324, 1194.6]",more pics overall 9 story 9 animation 9 sound ...,"(1.324, 1180.6]",story taking place 1 yr from where season 1 tr...
4,291149,aManOfCulture99,4181,\n \n \n \n ...,10,"{'Overall': '10', 'Story': '10', 'Animation': ...","(590.902, 7165.8]","(15.324, 1194.6]",more pics overall 10 story 10 animation 8 soun...,"(1.324, 1180.6]",kyoto animations greatest strength is being ab...
...,...,...,...,...,...,...,...,...,...,...,...
192107,240067,Unicorn819,1281,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '5', 'Animation': '1...","(590.902, 7165.8]","(15.324, 1194.6]",more pics overall 9 story 5 animation 10 sound...,"(1.324, 1180.6]",ok this anime is pretty old but here s the bac...
192108,285777,ShizzoSVH,1281,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '7', 'Animation': '9...","(590.902, 7165.8]","(15.324, 1194.6]",more pics overall 9 story 7 animation 9 sound ...,"(1.324, 1180.6]",the dub for this anime is made this anime a fu...
192109,286904,AlluMan96,1281,\n \n \n \n ...,3,"{'Overall': '3', 'Story': '3', 'Animation': '1...","(7165.8, 13675.6]","(1194.6, 2362.2]",more pics overall 3 story 3 animation 1 sound ...,"(1180.6, 2348.2]",some might argue that doing a review of a show...
192110,287903,AgentK300,1281,\n \n \n \n ...,10,"{'Overall': '10', 'Story': '3', 'Animation': '...","(590.902, 7165.8]","(15.324, 1194.6]",more pics overall 10 story 3 animation 3 sound...,"(1.324, 1180.6]",absolutely hilarious i accidentally came acros...
192111,299323,Scarlet012,1281,\n \n \n \n ...,9,"{'Overall': '9', 'Story': '7', 'Animation': '8...","(590.902, 7165.8]","(15.324, 1194.6]",more pics overall 9 story 7 animation 8 sound ...,"(1.324, 1180.6]",this will be a review for the english dubbed v...

In [39]:
df.columns

Index(['uid', 'profile', 'anime_uid', 'text', 'score', 'scores', 'char_count',
       'word_count', 'clean_text', 'clean_word_count', 'cleaner_text'],
      dtype='object')

In [40]:
df_model = df.drop(columns=['text', 'char_count', 'word_count', 'clean_text', 'clean_word_count'])

In [41]:
df_model

,uid,profile,anime_uid,score,scores,cleaner_text
0,255938,DesolatePsyche,34096,8,"{'Overall': '8', 'Story': '8', 'Animation': '8...",first things first my reviews system is explai...
1,259117,baekbeans,34599,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",let me start off by saying that made in abyss ...
2,253664,skrn,28891,7,"{'Overall': '7', 'Story': '7', 'Animation': '9...",art 9 10 it is great especially the actions du...
3,8254,edgewalker00,2904,9,"{'Overall': '9', 'Story': '9', 'Animation': '9...",story taking place 1 yr from where season 1 tr...
4,291149,aManOfCulture99,4181,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",kyoto animations greatest strength is being ab...
...,...,...,...,...,...,...
192107,240067,Unicorn819,1281,9,"{'Overall': '9', 'Story': '5', 'Animation': '1...",ok this anime is pretty old but here s the bac...
192108,285777,ShizzoSVH,1281,9,"{'Overall': '9', 'Story': '7', 'Animation': '9...",the dub for this anime is made this anime a fu...
192109,286904,AlluMan96,1281,3,"{'Overall': '3', 'Story': '3', 'Animation': '1...",some might argue that doing a review of a show...
192110,287903,AgentK300,1281,10,"{'Overall': '10', 'Story': '3', 'Animation': '...",absolutely hilarious i accidentally came acros...
192111,299323,Scarlet012,1281,9,"{'Overall': '9', 'Story': '7', 'Animation': '8...",this will be a review for the english dubbed v...

In [42]:
df_model.columns

Index(['uid', 'profile', 'anime_uid', 'score', 'scores', 'cleaner_text'], dtype='object')

In [43]:
df_model.columns = ['uid', 'profile', 'anime_uid', 'score', 'scores', 'text']

In [44]:
df_model['text'].sample(10)

53014     the reason i give this 1 score for overall is ...
122965    oh boy this did not fail to confuse the crap o...
172378    one of the good summer anime shows of 2011 the...
5645      yawns tl dr this is a good series watch it for...
73175     alluding as it may sound expectations are alwa...
59776     note rules say don t include story summaries u...
136463    this was the very first anime i ever saw! i ll...
66787     i can t understand why people rate this anime ...
27462     there are spoilers i think it was really good ...
4713      hayao miyazaki s work is and always will be ou...
Name: text, dtype: object

In [45]:
df_model['text'].sample(10)

93506     kyoukai senjou no horizon 2 this series is a g...
134446    finally it is here! the anime adaptation of ts...
48622     the pokemon anime often isn t very entertainin...
188       i though that i would not have given a chance ...
105177    red just like her hair the positives i beat my...
17620     i never quite understood what made assassinati...
32578     overview tatami galaxy is a very unusual anime...
38817     this is one of the best animes i have ever see...
30211     maquia is one of those anime which is frequent...
9861      before reading the rest of this review please ...
Name: text, dtype: object

In [46]:
df_model['text'].sample(10)

84457     plastic memories was a touching anime with str...
186400    we see the entire sao survivor roster return t...
148020    every season like many i scroll through the ca...
49039     okay gotta admit this one duped me more than a...
157301    i know my ratings look off the charts probably...
179063    when my best friend introduced me to gurren la...
139405    wellllll this kinda sucked lol let me ask a qu...
169955    no spoilers contained and sorry for my bad eng...
45484     winter of re birth the season of decay and dea...
190691    i was thirteen when i watched this and even th...
Name: text, dtype: object

In [47]:
def leftover(text):
    text = re.sub(r'\b(story|art)\s+\d+\b', '', text, flags=re.IGNORECASE)
    text = text.strip()

    return text

df_model['text'] = df_model['text'].apply(leftover)

In [48]:
df_model['text'].sample(10)

92685     heroic age is a mix between gundam and scifi b...
7444      ah drifters i ve been excited for this as a lo...
189386    the death busters arc is my favorite sailor mo...
151348    the more i watch the show the more i grow to l...
81495     originally published on anime viking http anim...
130213    what s important is what you do with the time ...
150234    i have come across a few interesting hentai ti...
78579     if there is a question about an anime that doe...
13050     this was a truly heart warming anime there isn...
82108     so this is my first review on this site so be ...
Name: text, dtype: object

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192112 entries, 0 to 192111
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   uid               192112 non-null  int64
 1   profile           192112 non-null  object
 2   anime_uid         192112 non-null  int64
 3   text              192112 non-null  object
 4   score             192112 non-null  int64
 5   scores            192112 non-null  object
 6   char_count        192112 non-null  category
 7   word_count        192112 non-null  category
 8   clean_text        192112 non-null  object
 9   clean_word_count  192112 non-null  category
 10  cleaner_text      192112 non-null  object
dtypes: category(3), int64(3), object(5)
memory usage: 12.3+ MB

In [50]:
df_model

,uid,profile,anime_uid,score,scores,text
0,255938,DesolatePsyche,34096,8,"{'Overall': '8', 'Story': '8', 'Animation': '8...",first things first my reviews system is explai...
1,259117,baekbeans,34599,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",let me start off by saying that made in abyss ...
2,253664,skrn,28891,7,"{'Overall': '7', 'Story': '7', 'Animation': '9...",10 it is great especially the actions during t...
3,8254,edgewalker00,2904,9,"{'Overall': '9', 'Story': '9', 'Animation': '9...",story taking place 1 yr from where season 1 tr...
4,291149,aManOfCulture99,4181,10,"{'Overall': '10', 'Story': '10', 'Animation': ...",kyoto animations greatest strength is being ab...
...,...,...,...,...,...,...
192107,240067,Unicorn819,1281,9,"{'Overall': '9', 'Story': '5', 'Animation': '1...",ok this anime is pretty old but here s the bac...
192108,285777,ShizzoSVH,1281,9,"{'Overall': '9', 'Story': '7', 'Animation': '9...",the dub for this anime is made this anime a fu...
192109,286904,AlluMan96,1281,3,"{'Overall': '3', 'Story': '3', 'Animation': '1...",some might argue that doing a review of a show...
192110,287903,AgentK300,1281,10,"{'Overall': '10', 'Story': '3', 'Animation': '...",absolutely hilarious i accidentally came acros...
192111,299323,Scarlet012,1281,9,"{'Overall': '9', 'Story': '7', 'Animation': '8...",this will be a review for the english dubbed v...

In [51]:
df_model.to_csv('After_EDA_data/Light_text.csv', index=False)